###List All Messages
GET http://localhost:3006/messages

###Add New Messages
POST http://localhost:3006/messages
Content-Type: application/json

{
    "content": "a7eeh"
}

###List a Message
GET http://localhost:3006/messages/71284
